"""
=========================================================
                SALES DATA ANALYSIS PROJECT
=========================================================

Intern Name : Ayush Raina
Dataset     : April 2019 Sales Data
Language    : Python

Libraries Used:
1. Pandas
2. Matplotlib

Objective:
To analyze April 2019 sales data and generate useful
business insights through data cleaning, analysis,
and visualization.

=========================================================
"""

# =========================================================
# IMPORT LIBRARIES
# =========================================================

import pandas as pd
import matplotlib.pyplot as plt


# =========================================================
# LOAD DATASET
# =========================================================

df = pd.read_csv("data/sales_data.csv")

print("=" * 60)
print("DATASET LOADED SUCCESSFULLY")
print("=" * 60)

print("Original Shape :", df.shape)


# =========================================================
# DATA CLEANING
# =========================================================

# Remove missing values
df = df.dropna()

# Remove repeated header rows
df = df[df["Order ID"] != "Order ID"]

# Remove duplicate rows
df = df.drop_duplicates()

print("\nAfter Cleaning :", df.shape)


# =========================================================
# DATA TYPE CONVERSION
# =========================================================

df["Quantity Ordered"] = df["Quantity Ordered"].astype(int)
df["Price Each"] = df["Price Each"].astype(float)

# Convert Order Date to datetime
df["Order Date"] = pd.to_datetime(df["Order Date"])


# =========================================================
# FEATURE ENGINEERING
# =========================================================

# Create Sales column
df["Sales"] = df["Quantity Ordered"] * df["Price Each"]

# Extract Month
df["Month"] = df["Order Date"].dt.month

# Extract Hour
df["Hour"] = df["Order Date"].dt.hour

# Extract City
df["City"] = df["Purchase Address"].apply(lambda x: x.split(",")[1].strip())


# =========================================================
# BASIC DATA INFORMATION
# =========================================================

print("\n" + "=" * 60)
print("DATASET INFORMATION")
print("=" * 60)

print(df.info())

print("\nColumn Names")
print(df.columns.tolist())


# =========================================================
# MONTHLY SALES ANALYSIS
# =========================================================

monthly_sales = df.groupby("Month")["Sales"].sum()

print("\n" + "=" * 60)
print("MONTHLY SALES")
print("=" * 60)

print(monthly_sales)

plt.figure(figsize=(8,5))

monthly_sales.plot(
    kind="bar",
    color="orange"
)

plt.title("Monthly Sales Revenue")
plt.xlabel("Month")
plt.ylabel("Revenue ($)")
plt.grid(axis="y")

plt.tight_layout()

plt.savefig("images/monthly_sales.png")

plt.show()


# =========================================================
# SALES BY CITY
# =========================================================

city_sales = df.groupby("City")["Sales"].sum().sort_values(ascending=False)

print("\n" + "=" * 60)
print("SALES BY CITY")
print("=" * 60)

print(city_sales)

plt.figure(figsize=(10,6))

city_sales.sort_values().plot(
    kind="bar",
    color="green"
)

plt.title("Sales Revenue by City")
plt.xlabel("City")
plt.ylabel("Revenue ($)")
plt.xticks(rotation=45)
plt.grid(axis="y")

plt.tight_layout()

plt.savefig("images/city_sales.png")

plt.show()


# =========================================================
# BEST SELLING PRODUCTS
# =========================================================

product_sales = df.groupby("Product")["Quantity Ordered"].sum().sort_values(ascending=False)

print("\n" + "=" * 60)
print("BEST SELLING PRODUCTS")
print("=" * 60)

print(product_sales)

plt.figure(figsize=(12,6))

product_sales.plot(
    kind="bar",
    color="purple"
)

plt.title("Best Selling Products")
plt.xlabel("Product")
plt.ylabel("Quantity Sold")
plt.xticks(rotation=90)
plt.grid(axis="y")

plt.tight_layout()

plt.savefig("images/best_selling_products.png")

plt.show()


# =========================================================
# REVENUE BY PRODUCT
# =========================================================

product_revenue = df.groupby("Product")["Sales"].sum().sort_values(ascending=False)

print("\n" + "=" * 60)
print("REVENUE BY PRODUCT")
print("=" * 60)

print(product_revenue)

plt.figure(figsize=(12,6))

product_revenue.plot(
    kind="bar",
    color="royalblue"
)

plt.title("Revenue Generated by Product")
plt.xlabel("Product")
plt.ylabel("Revenue ($)")
plt.xticks(rotation=90)
plt.grid(axis="y")

plt.tight_layout()

plt.savefig("images/revenue_by_product.png")

plt.show()


# =========================================================
# SALES BY HOUR
# =========================================================

hourly_sales = df.groupby("Hour")["Sales"].sum()

print("\n" + "=" * 60)
print("SALES BY HOUR")
print("=" * 60)

print(hourly_sales)

plt.figure(figsize=(10,5))

hourly_sales.plot(
    marker="o",
    color="red"
)

plt.title("Sales by Hour")
plt.xlabel("Hour")
plt.ylabel("Revenue ($)")
plt.grid(True)

plt.tight_layout()

plt.savefig("images/hourly_sales.png")

plt.show()


# =========================================================
# TOP 5 PRODUCT DISTRIBUTION
# =========================================================

top_products = (
    df.groupby("Product")["Quantity Ordered"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

plt.figure(figsize=(8,8))

plt.pie(
    top_products,
    labels=top_products.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Top 5 Product Distribution")

plt.savefig("images/product_distribution.png")

plt.show()


# =========================================================
# SUMMARY STATISTICS
# =========================================================

print("\n" + "=" * 60)
print("PROJECT SUMMARY")
print("=" * 60)

print(f"Total Revenue        : ${df['Sales'].sum():,.2f}")

print(f"Average Order Value  : ${df['Sales'].mean():,.2f}")

print(f"Total Orders         : {df.shape[0]}")

print(f"Unique Products      : {df['Product'].nunique()}")

print(f"Cities Covered       : {df['City'].nunique()}")

print("\nProject Completed Successfully!")